$(document).ready(function(){
    $(".L1").mouseover(function(){
        $(".U1").css("display","block");
    });
    $(".L1").mouseout(function(){
        $(".U1").css("display","none");
    });
    $(".L2").mouseover(function(){
        $(".U2").css("display","block");
    });
    $(".L2").mouseout(function(){
        $(".U2").css("display","none");
    });
    $(".L3").mouseover(function(){
        $(".U3").css("display","block");
    });
    $(".L3").mouseout(function(){
        $(".U3").css("display","none");
    });
});
